---
abstract: 'Upload files to a Sonatype Nexus instance. Modelled on L<CPAN::Uploader>.'
author:
  - 'Brad Macpherson <brad@teched-creations.com>'
build_requires:
  Pod::Coverage::TrustPod: '0'
  Test::More: '1.00'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Nexus-Uploader
requires:
  Carp: '0'
  Data::Dumper: '0'
  JSON: '0'
  Log::Any: '0'
  MIME::Base64: '0'
  Moose: '0'
  REST::Client: '0'
  namespace::autoclean: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
version: 0.0.1
